---
- name: Remove nginx test
  hosts: test
  gather_facts: yes

  tasks:
  - name: remove epel-release
    yum: name=epel-release state=absent
  - name: remove nginx web server
    yum: name=nginx state=absent
