---
- name: Install zabbix-agent-5
  hosts: test
  remote_user: root
  tasks:
   - name: Test Connection
     ping:
   - name: Download zabbix-agent
     get_url:
      url: http://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      dest: /root/
   - name: Install Zabbix-agent
     yum:
      name:
       - /root/zabbix-release-5.0-1.el7.noarch.rpm
       - zabbix-agent
   - name: Zabbix-Agent Start
     systemd:
      state: started
      name: zabbix-agent
